#!/usr/bin/ruby

# Write with ./brkt
# Why waste all that space typing {sc CIA}?
# when a simple search/replace script will take care of it?
#
# USAGE:
#
#	$ cat file.txt | smcps | brkt | markdown > file.html
#

ARGF.set_encoding(Encoding::UTF_8)
input = ARGF.read

# DEFINE ABBREVIATIONS
list = /\b(AI|ASI|CIA|DOD|FBI|IQ|NASA|NSA|QALM|US)\b/x

# Substitute HTML + lowercase
input = input.gsub(/(#{list})/, "{sc " + '\1' + "}")

print input
